Default:
    class:
    modelargs: {}
    pretrain: ~
    dataset_class: ImageDataset
    nframes: 1
    chopable: false
    need_pad: false
    model_scale: 1
    frame_scale: 1
    saveimg_function: sdr
    description: ''
